# Workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages

on:
  # Trigger the workflow on push to the default branch
  push:
    branches: ["main"]  # Update this if your default branch is different

  # Allow manual triggers from the Actions tab
  workflow_dispatch:

# Permissions required for deployment
permissions:
  contents: read      # Read repository content
  pages: write        # Write to GitHub Pages
  id-token: write     # Required for authentication

# Control concurrency to avoid conflicts during deployments
concurrency:
  group: "pages"         # Grouping by deployment type
  cancel-in-progress: false  # Do not cancel ongoing deployments

jobs:
  # Job to build the Jekyll site
  build:
    runs-on: ubuntu-latest  # Specify the environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure the correct version of the checkout action

      - name: Setup Pages environment
        uses: actions/configure-pages@v3  # Ensure compatibility with GitHub Pages

      - name: Build the Jekyll site
        uses: actions/jekyll-build-pages@v1  # Uses preinstalled Jekyll environment
        with:
          source: ./
          destination: ./_site  # Build output directory

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1  # Upload the _site folder for deployment

  # Job to deploy the site
  deploy:
    environment:
      name: github-pages  # Deployment environment
      url: ${{ steps.deployment.outputs.page_url }}  # GitHub Pages URL
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1  # Deploy the uploaded artifact
